# Generated by Django 4.0.1 on 2022-03-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialRecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeType', models.IntegerField()),
                ('departmentID', models.IntegerField()),
                ('isEmployee', models.BooleanField()),
                ('employeeNumber', models.IntegerField()),
                ('employeePIN', models.IntegerField()),
                ('employeeHourlyRate', models.FloatField()),
                ('employeeTotalHoursPayout', models.FloatField()),
            ],
        ),
    ]
